document.addEventListener("DOMContentLoaded", () => {
  console.log("feedback.js loaded!");

  const form = document.getElementById("feedbackForm");
  const preview = document.getElementById("jsonPreview");
  const autoBtn = document.getElementById("autoGenerateBtn");
  const autoTextArea = document.getElementById("autoGeneratedText");

  // Render 백엔드 URL
  const BACKEND_URL = "https://joyjoy-feedback-backend.onrender.com";

  // ===============================================================
  // 1) 기존: 수동 "서버로 전송 + JSON 미리보기" (원래 기능 유지)
  //    - 필요하면 나중에 없애도 됨
  // ===============================================================
  form.addEventListener("submit", async (e) => {
    e.preventDefault();

    const data = {
      childName: form.childName.value,
      ageMonth: form.ageMonth.value,
      items: {
        item1: form.item1.value,
        // 필요하면 item2~6도 여기에 추가 가능
      }
    };

    // JSON 미리보기 표시
    preview.textContent = JSON.stringify(data, null, 2);

    try {
      const response = await fetch(`${BACKEND_URL}/api/feedback`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data)
      });

      const result = await response.json();
      console.log("서버 응답:", result);

      alert("서버 전송 성공!");

    } catch (err) {
      console.error("전송 오류:", err);
      alert("서버 전송 실패");
    }
  });

  // ===============================================================
  // 2) AI 자동 생성 + 자동 서버 저장 (한 번에 처리)
  // ===============================================================
  if (autoBtn) {
    autoBtn.addEventListener("click", async () => {
      // 1단계: 자동 생성용 점수/정보 모으기
      const autoData = {
        childName: form.childName.value,
        ageMonth: form.ageMonth.value,
        item1: form.item1 ? form.item1.value : "",
        item2: form.item2 ? form.item2.value : "",
        item3: form.item3 ? form.item3.value : "",
        item4: form.item4 ? form.item4.value : "",
        item5: form.item5 ? form.item5.value : "",
        item6: form.item6 ? form.item6.value : ""
      };

      console.log("자동 생성 요청 데이터:", autoData);

      try {
        // 2단계: /api/auto-feedback 호출 → 자동 문장 생성
        const autoRes = await fetch(`${BACKEND_URL}/api/auto-feedback`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(autoData)
        });

        // 디버깅용: 원시 응답 확인 (문제 생기면 주석 해제해서 확인해도 됨)
        // const rawText = await autoRes.text();
        // console.log("raw auto-feedback response:", rawText);
        // const autoResult = JSON.parse(rawText);

        const autoResult = await autoRes.json();
        console.log("AI 자동 생성 결과:", autoResult);

        // textarea에 자동 생성된 문장 넣기
        if (autoTextArea && autoResult.autoText) {
          autoTextArea.value = autoResult.autoText;
        }

        // 3단계: 자동 생성 결과 + 점수를 묶어서 /api/feedback 으로 저장
        const saveData = {
          childName: autoData.childName,
          ageMonth: autoData.ageMonth,
          autoText: autoResult.autoText || "",
          items: {
            item1: autoData.item1,
            item2: autoData.item2,
            item3: autoData.item3,
            item4: autoData.item4,
            item5: autoData.item5,
            item6: autoData.item6
          }
        };

        // JSON 미리보기에도 최종 저장 내용을 보여주기
        if (preview) {
          preview.textContent = JSON.stringify(saveData, null, 2);
        }

        const saveRes = await fetch(`${BACKEND_URL}/api/feedback`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(saveData)
        });

        const saveResult = await saveRes.json();
        console.log("자동 생성 후 서버 저장 응답:", saveResult);

        alert("AI 자동 문장 생성 및 서버 저장이 완료되었어요!");

      } catch (err) {
        console.error("AI 자동 생성 또는 저장 중 오류:", err);
        alert("AI 자동 생성 또는 서버 저장 중 오류가 발생했어요.");
      }
    });
  }
});

