document.addEventListener("DOMContentLoaded", () => {
  console.log("feedback.js loaded!");

  const form = document.getElementById("feedbackForm");
  const preview = document.getElementById("jsonPreview");
  const autoBtn = document.getElementById("autoGenerateBtn");
  const autoTextArea = document.getElementById("autoGeneratedText");

  // Render 백엔드 URL
  const BACKEND_URL = "https://joyjoy-feedback-backend.onrender.com";

  // ===============================================================
  // 1) 기존: 수동 "서버로 전송 + JSON 미리보기" (원래 기능 유지)
  //    - 필요하면 나중에 없애도 됨
  // ===============================================================
  form.addEventListener("submit", async (e) => {
    e.preventDefault();

    const data = {
      childName: form.childName.value,
      ageMonth: form.ageMonth.value,
      items: {
        item1: form.item1.value,
        // 필요하면 item2~6도 여기에 추가 가능
      }
    };

    // JSON 미리보기 표시
    preview.textContent = JSON.stringify(data, null, 2);

    try {
      const response = await fetch(`${BACKEND_URL}/api/feedback`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data)
      });

      const result = await response.json();

      console.log("서버 응답:", result);

      alert("서버 전송 성공!");

    } catch (err) {
      console.error("전송 오류:", err);
      alert("서버 전송 실패");
    }
  });

  // ===============================================================
  // 2) AI 자동 생성 + 자동 서버 저장 (한 번에 처리)
  // ===============================================================
  if (autoBtn) {
    autoBtn.addEventListener("click", async () => {
      // 1단계: 자동 생성용 점수/정보 모으기
      const autoData = {
        childName: form.childName.value,
        ageMonth: form.ageMonth.value,
        item1: form.item1 ? form.item1.value : "",
        item2: form.item2 ? form.item2.value : "",
        item3: form.item3 ? form.item3.value : "",
        item4: form.item4 ? form.item4.value : "",
        item5: form.item5 ? form.item5.value : "",
        item6: form.item6 ? form.item6.value : ""
      };

      console.log("자동 생성 요청 데이터:", autoData);

      try {
        // 2단계: /api/auto-feedback 호출 → 자동 문장 생성
        const autoRes = await fetch(`${BACKEND_URL}/api/auto-feedback`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(autoData)
        });



        // 1) 우선 raw 텍스트로 받아서 로그 찍기 (디버깅용)
        const raw = await autoRes.text();
        console.log("auto-feedback raw response:", raw);

        // 2) HTTP 에러 상태인 경우
        if (!autoRes.ok) {
          alert("AI 자동 생성 요청 중 오류가 발생했어요.");
          throw new Error(`auto-feedback HTTP error: ${autoRes.status}`);
        }

        // 3) JSON 파싱 (서버가 HTML을 보내는 경우 방어)
        let autoResult;
        try {
          autoResult = JSON.parse(raw);
        } catch (e) {
          console.error("auto-feedback JSON 파싱 실패:", e);
          alert("AI 자동 생성 응답을 해석하는 중 오류가 발생했어요.");
          throw e;
        }

        console.log("AI 자동 생성 결과(JSON):", autoResult);

        // 4) LLM 문장 + 백업 문장 중에서 최종 문장 선택
        const finalText =
          autoResult.autoText ||      // LLM이 만든 문장
          autoResult.backupText ||    // 백업: 템플릿 기반 문장
          "오늘 수업 참여 모습을 정리하는 중 오류가 발생했어요.";

        // textarea에 자동 생성된 문장 넣기
        if (autoTextArea) {
          autoTextArea.value = finalText;
        }


        // 5) 자동 생성 결과 + 점수를 묶어서 /api/feedback 으로 저장
        const saveData = {
          childName: autoData.childName,
          ageMonth: autoData.ageMonth,
          autoText: autoResult.autoText || "",
          items: {
            item1: autoData.item1,
            item2: autoData.item2,
            item3: autoData.item3,
            item4: autoData.item4,
            item5: autoData.item5,
            item6: autoData.item6
          }
        };

        // JSON 미리보기에도 최종 저장 내용을 보여주기
        if (preview) {
          preview.textContent = JSON.stringify(saveData, null, 2);
        }

        // /api/feedback 으로 저장 요청
        const saveRes = await fetch(`${BACKEND_URL}/api/feedback`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(saveData)
        });

        const saveRaw = await saveRes.text();
        console.log("feedback save raw response:", saveRaw);

        let saveResult;
        try {
          saveResult = JSON.parse(saveRaw);
        } catch (e) {
          console.error("피드백 저장 응답 JSON 파싱 실패:", e);
          // 저장 결과는 크게 중요하지 않다면 여기서 바로 alert만 띄워도 됨
        }

        if (!saveRes.ok) {
          alert("AI 문장은 생성되었지만 서버 저장 중 오류가 발생했어요.");
        } else {
          console.log("자동 생성 후 서버 저장 응답:", saveResult);
          alert("AI 자동 문장 생성 및 서버 저장이 완료되었어요!");
        }

      } catch (err) {
        console.error("AI 자동 생성 또는 저장 중 오류:", err);
        alert("AI 자동 생성 또는 서버 저장 중 오류가 발생했어요.");
      }
    });
  }
});

