// === line1, line2를 feedback_items.json에서 읽어서 HTML에 채우는 함수들 ===
async function loadActivityLines() {
  try {
    const res = await fetch("items/feedback_items.json", { cache: "no-cache" });
    if (!res.ok) {
      console.error("❌ feedback_items.json 요청 실패:", res.status, res.statusText);
      return;
    }

    const data = await res.json();
    console.log("✅ feedback_items.json 로드 완료:", data);

    fillActivity("item1", data.item1);
    fillActivity("item2", data.item2);
    fillActivity("item3", data.item3);
    fillActivity("item4", data.item4);
    fillActivity("item5", data.item5);
    fillActivity("item6", data.item6);
  } catch (err) {
    console.error("❌ feedback_items.json 불러오는 중 오류:", err);
  }
}

function fillActivity(itemKey, itemData) {
  if (!itemData) return;

  const line1El = document.getElementById(`${itemKey}-line1`);
  const line2El = document.getElementById(`${itemKey}-line2`);

  if (line1El) line1El.textContent = itemData.line1 || "";
  if (line2El) line2El.textContent = itemData.line2 || "";

  const optionsContainer = document.getElementById(`${itemKey}-options`);
  if (optionsContainer && itemData.options) {
    optionsContainer.innerHTML = generateRadioButtons(itemKey, itemData.options);
  }
}

function generateRadioButtons(name, options) {
  let html = "";

  options.forEach((opt, i) => {
    const id = `${name}-option-${opt.value}`;
    html += `
      <label for="${id}">
        <input type="radio" name="${name}" value="${opt.value}" id="${id}" ${i === 0 ? "checked" : ""}>
        ${opt.label}
      </label><br>
    `;
  });

  return html;
}

// ===================================================================
// DOM LOAD
// ===================================================================
document.addEventListener("DOMContentLoaded", () => {
  console.log("feedback.js loaded!");
  loadActivityLines();

  const form = document.getElementById("feedbackForm");
  const autoBtn = document.getElementById("autoGenerateBtn");
  const autoTextArea = document.getElementById("autoGeneratedText");

  const BACKEND_URL = "https://joyjoy-feedback-backend.onrender.com";

  if (!form) return;

  // ===============================================================
  // 1) AI 자동 생성 버튼 클릭
  // ===============================================================
  autoBtn?.addEventListener("click", async (e) => {
    e.preventDefault();
    console.log("🤖 AI 자동 생성 클릭!");

    // 🔥 선택된 value를 items 배열에 담기 (핵심 수정)
    const itemsArray = [
      { id: 1, value: form.item1?.value || "" },
      { id: 2, value: form.item2?.value || "" },
      { id: 3, value: form.item3?.value || "" },
      { id: 4, value: form.item4?.value || "" },
      { id: 5, value: form.item5?.value || "" },
      { id: 6, value: form.item6?.value || "" }
    ];

    const payload = {
      childName: form.childName?.value || "",
      ageMonth: Number(form.ageMonth?.value || 0),
      items: itemsArray
    };

    console.log("📤 AI 자동 생성 payload:", payload);

    try {
      const autoRes = await fetch(`${BACKEND_URL}/api/auto-feedback`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload)
      });

      const raw = await autoRes.text();
      let autoResult;

      try {
        autoResult = JSON.parse(raw);
      } catch (e) {
        console.error("JSON 파싱 실패:", e);
        alert("AI 응답을 해석할 수 없습니다.");
        return;
      }

      const finalText =
        autoResult.autoText ||
        autoResult.backupText ||
        "오늘의 피드백 생성 중 오류가 발생했습니다.";

      if (autoTextArea) autoTextArea.value = finalText;

      // 저장용 데이터 구성
      const saveData = {
        ...payload,
        autoText: finalText
      };

      console.log("📤 저장용 saveData:", saveData);

      await fetch(`${BACKEND_URL}/api/feedback`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(saveData)
      });

      alert("AI 자동 생성 + 저장 완료!");

    } catch (err) {
      console.error("AI 자동 생성 오류:", err);
      alert("AI 자동 생성 중 오류");
    }
  });
});
